-- New survey battery tables (REI-40, CFQ, OCI-R, BFI-2-S)
-- Run on the MySQL `basile` database. Mirrors spaceprl_cfi / spaceprl_cfs.

CREATE TABLE spaceprl_rei40 (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  prolificID  VARCHAR(64)  NOT NULL,
  expName     VARCHAR(64),
  timestamp   DATETIME,
  surveyOrder VARCHAR(32),
  q0  TINYINT, q1  TINYINT, q2  TINYINT, q3  TINYINT, q4  TINYINT,
  q5  TINYINT, q6  TINYINT, q7  TINYINT, q8  TINYINT, q9  TINYINT,
  q10 TINYINT, q11 TINYINT, q12 TINYINT, q13 TINYINT, q14 TINYINT,
  q15 TINYINT, q16 TINYINT, q17 TINYINT, q18 TINYINT, q19 TINYINT,
  q20 TINYINT, q21 TINYINT, q22 TINYINT, q23 TINYINT, q24 TINYINT,
  q25 TINYINT, q26 TINYINT, q27 TINYINT, q28 TINYINT, q29 TINYINT,
  q30 TINYINT, q31 TINYINT, q32 TINYINT, q33 TINYINT, q34 TINYINT,
  q35 TINYINT, q36 TINYINT, q37 TINYINT, q38 TINYINT, q39 TINYINT
);

CREATE TABLE spaceprl_cfq (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  prolificID  VARCHAR(64)  NOT NULL,
  expName     VARCHAR(64),
  timestamp   DATETIME,
  surveyOrder VARCHAR(32),
  q0  TINYINT, q1  TINYINT, q2  TINYINT, q3  TINYINT, q4  TINYINT,
  q5  TINYINT, q6  TINYINT, q7  TINYINT, q8  TINYINT, q9  TINYINT,
  q10 TINYINT, q11 TINYINT, q12 TINYINT, q13 TINYINT, q14 TINYINT,
  q15 TINYINT, q16 TINYINT, q17 TINYINT, q18 TINYINT, q19 TINYINT,
  q20 TINYINT, q21 TINYINT, q22 TINYINT, q23 TINYINT, q24 TINYINT
);

CREATE TABLE spaceprl_ocir (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  prolificID  VARCHAR(64)  NOT NULL,
  expName     VARCHAR(64),
  timestamp   DATETIME,
  surveyOrder VARCHAR(32),
  q0  TINYINT, q1  TINYINT, q2  TINYINT, q3  TINYINT, q4  TINYINT,
  q5  TINYINT, q6  TINYINT, q7  TINYINT, q8  TINYINT, q9  TINYINT,
  q10 TINYINT, q11 TINYINT, q12 TINYINT, q13 TINYINT, q14 TINYINT,
  q15 TINYINT, q16 TINYINT, q17 TINYINT
);

CREATE TABLE spaceprl_bfi2s (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  prolificID  VARCHAR(64)  NOT NULL,
  expName     VARCHAR(64),
  timestamp   DATETIME,
  surveyOrder VARCHAR(32),
  q0  TINYINT, q1  TINYINT, q2  TINYINT, q3  TINYINT, q4  TINYINT,
  q5  TINYINT, q6  TINYINT, q7  TINYINT, q8  TINYINT, q9  TINYINT,
  q10 TINYINT, q11 TINYINT, q12 TINYINT, q13 TINYINT, q14 TINYINT,
  q15 TINYINT, q16 TINYINT, q17 TINYINT, q18 TINYINT, q19 TINYINT,
  q20 TINYINT, q21 TINYINT, q22 TINYINT, q23 TINYINT, q24 TINYINT,
  q25 TINYINT, q26 TINYINT, q27 TINYINT, q28 TINYINT, q29 TINYINT
);
